ModAPI.registerAPI("FirefliesAPI", {
    MathHelper,
    RenderHelper,
    RenderSide,
    BlockAnimation,
    EDestroyLevel,
    Vector3,
    ItemStack,
    BasicBlock,
    BlockModel,
    BlockPlant,
    BlockBush,
    Keyboard,
    UIHelper,
    PlayerUser,
    Bark,
    Hewn,
    Log,
    Planks,
    RotatableLog,
    BasicItem,
    CommonTileEntity,
    LocalTileEntity,
    NetworkEvent,
    ContainerEvent,
    BasicDimension,
    RuntimeData,
    EScreenName,
    ECallback,
    ESide,
    WorldRenderObject,
    SubscribeEvent,
    requireGlobal(command: string) {
		return eval(command);
	}
});